build-VoltF0.3-Project:
 stage: build
 image: trion/ng-cli
 only:
 - Volt-F0.3
 before_script:
  - echo "Iniciando la compilación del código"
 #- cd frontend-nielsen-dev/frontend-nielsen-dev
  - npm ci
 script:
  - ng build --configuration=dev-ref3
  - echo "$PRIVATE_KEY_DEVREF3" > devref3.key
  - chmod 600 devref3.key 
  - cd dist/app-nielsen/
  - ssh-agent bash -c -v 'ssh-add ../../devref3.key; scp -o StrictHostKeyChecking=no -r * developer@143.198.16.105:/var/www/html/'