build-VoltF0.3-Project:
 stage: build
 image: trion/ng-cli
 only:
 - Volt-F0.3
 before_script:
  - echo "Iniciando la compilación del código"
 #- cd frontend-nielsen-dev/frontend-nielsen-dev
  - npm ci
  - GENERATE_SOURCEMAP=false
 script:
  - node --max_old_space_size=3072 node_modules/@angular/cli/bin/ng build --configuration=dev-refcuba
  - echo "$PRIVATE_KEY_DEVREFCUBA" > devrefcuba.key
  - chmod 600 devrefcuba.key 
  - cd dist/app-nielsen/
  - ssh-agent bash -c -v 'ssh-add ../../devrefcuba.key; scp -o StrictHostKeyChecking=no -r * developer@143.198.16.105:/var/www/html/'