export interface Referer {
    id:string,
    rut: string,
    name: string,
    lastName: string,
    secondLastName: string,
    email : string,
    phone : string,
    serviceType : string,
    service : string,
    serviceName : string,
    profit : number,
    profitOriginal : number,
    promotion : string,
    status: number,
    step: number,
    information: string,
    seller: string,
    referent: string,
    updatedAt: Date;
    cantidadServicios: number,
}
