name: Angular deployment
on:
  push:
    branches:
      - fb4

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "npm"
      
      - name: Intall dependencies and build
        run: npm ci && npm run build:fb4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.FB4_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.FB4_KNOWN_HOSTS }}

      - name: Deploy using rsync
        run: rsync -avz ./dist/cuba/ ${{ secrets.FB4_SSH_USER }}@${{ secrets.FB4_SSH_HOST }}:/var/www/tuercas/
