name: Angular deployment.
on:
  push:
    branches:  ["dev"]
       
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "npm"
      
      - name: Install dependencies and build
        run: npm ci && npm run build:dev

      -  name: Ver por consola variables de entorno
         run: |
            echo "key: ${secrets.SUBDEV_SSH_PRIVATE_KEY}"
            echo "knwon_hosts: ${secrets.SUBDEV_KNOWN_HOSTS}"
          
        
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.SUBDEV_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SUBDEV_KNOWN_HOSTS }}

      - name: Deploy using rsync
        run: rsync -avz ./dist/cuba/ ${{ secrets.SUBDEV_SSH_USER }}@${{ secrets.SUBDEV_SSH_HOST }}:/var/www/lgs



  
